on: push
jobs:
  build-node: 
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - run: node --version
      - run: npm --version
      - run: actions/checkout@v3
      - run: npm install --force
      - run: npm run start
      
