on: push ## Acontece toda vez que fazemos um push
jobs:
  build-node: 
    runs-on: ubuntu-latest
    container: node:22
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: echo project ready 🚀
      
